export interface IUserData {
  avatar_url: string;
  bio: unknown;
  blog: string;
  company: unknown;
  created_at: Date | string;
  email: unknown;
  events_url: string;
  followers: number;
  followers_url: string;
  following: number;
  following_url: string;
  gists_url: string;
  gravatar_id: string;
  hireable: unknown;
  html_url: string;
  id: number;
  location: unknown;
  login: string;
  name: unknown;
  node_id: string;
  organizations_url: string;
  public_gists: number;
  public_repos: number;
  received_events_url: string;
  repos_url: string;
  site_admin: false;
  starred_url: string;
  subscriptions_url: string;
  twitter_username: unknown;
  type: string;
  updated_at: Date | string;
  url: string;
}
